# Gitlab CI/CD Variables needed for this pipeline

# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_DEFAULT_REGION

stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - echo "Starting pipeline..."

build:
  stage: build
  image: python:3.12
  script:
    - echo "Building app..."
    - >
      pip install --platform manylinux2014_x86_64 -t lib -r requirements.txt --only-binary=:all: --upgrade
    - zip lambda_function.zip -r lib/.
    - zip lambda_function.zip -u $CI_PROJECT_DIR/api/*.py
  artifacts:
    paths:
      - lambda_function.zip
      - lib
    expire_in: 1 day

deploy:
  stage: deploy
  image: python:3.12
  script:
    - echo "Deploying to AWS Lambda..."
  when: manual

.global_rules:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
