version: "3.8"
services:
  python:
    container_name: sgc-api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sgc-api:1.0.0
    volumes:
      - ./:/code
    env_file:
      - .env
    ports:
      - "8000:80"
    restart: unless-stopped
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sgc-sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ./db:/config
    ports:
      - 3000:3000
    restart: unless-stopped
